import type { SchemaTypeDefinition } from "sanity";
import {
  ctaBlock,
  faqEntry,
  faqSection,
  imageWithAlt,
  localeString,
  localeStringList,
  localeText,
  principleItem,
  principlesSection,
  seoFields,
  specItem,
  workflowSection,
  workflowStep,
} from "./objects";
import {
  aboutPage,
  author,
  blogPost,
  caseStudy,
  certificate,
  clientLogo,
  eventItem,
  founder,
  homePage,
  milestone,
  newsItem,
  partner,
  product,
  productCategory,
  redirect,
  seoEntry,
  service,
  siteSettings,
  solutionChild,
  solutionGroup,
  stat,
  testimonial,
  uiMessages,
} from "./documents";

export const schemaTypes: SchemaTypeDefinition[] = [
  // Objects
  localeString,
  localeText,
  localeStringList,
  imageWithAlt,
  specItem,
  principleItem,
  workflowStep,
  faqEntry,
  principlesSection,
  workflowSection,
  faqSection,
  ctaBlock,
  seoFields,
  // Singletons
  siteSettings,
  homePage,
  aboutPage,
  // Collections
  service,
  partner,
  certificate,
  stat,
  milestone,
  founder,
  testimonial,
  newsItem,
  caseStudy,
  eventItem,
  clientLogo,
  author,
  blogPost,
  productCategory,
  product,
  solutionGroup,
  solutionChild,
  seoEntry,
  uiMessages,
  redirect,
];

export const singletonTypes = new Set(["siteSettings", "homePage", "aboutPage"]);
