import type { SchemaTypeDefinition } from "sanity";
import {
  ctaBlock,
  faqEntry,
  faqSection,
  imageWithAlt,
  localeString,
  localeStringList,
  localeText,
  principleItem,
  principlesSection,
  seoFields,
  specItem,
  workflowSection,
  workflowStep,
} from "./objects";
import {
  beforeAfterContent,
  companyValueItem,
  engineeringCapabilityCard,
  engineeringCapabilitiesSection,
  homeHeroCopy,
  missionVisionBlock,
  pageCta,
  pageHero,
  promoSection,
  quoteBlock,
  sectionHeader,
  standardItem,
  productExplorerLabels,
  productDetailLabels,
  solutionChildLabels,
  timelineSectionBlock,
} from "./page-sections";
import {
  aboutPage,
  author,
  blogPage,
  blogPost,
  caseStudy,
  certificate,
  clientLogo,
  contactPage,
  eventItem,
  formSubmission,
  founder,
  homePage,
  milestone,
  newsItem,
  partner,
  product,
  productCategory,
  productsPage,
  redirect,
  seoEntry,
  service,
  siteSettings,
  solutionChild,
  solutionGroup,
  solutionsPage,
  stat,
  testimonial,
  uiMessages,
} from "./documents";

export const schemaTypes: SchemaTypeDefinition[] = [
  // Objects
  localeString,
  localeText,
  localeStringList,
  imageWithAlt,
  specItem,
  principleItem,
  workflowStep,
  faqEntry,
  principlesSection,
  workflowSection,
  faqSection,
  ctaBlock,
  seoFields,
  sectionHeader,
  pageHero,
  homeHeroCopy,
  quoteBlock,
  promoSection,
  beforeAfterContent,
  missionVisionBlock,
  standardItem,
  companyValueItem,
  engineeringCapabilityCard,
  engineeringCapabilitiesSection,
  pageCta,
  productExplorerLabels,
  productDetailLabels,
  solutionChildLabels,
  timelineSectionBlock,
  // Singletons
  siteSettings,
  homePage,
  aboutPage,
  contactPage,
  productsPage,
  solutionsPage,
  blogPage,
  // Collections
  service,
  partner,
  certificate,
  stat,
  milestone,
  founder,
  testimonial,
  newsItem,
  caseStudy,
  eventItem,
  clientLogo,
  author,
  blogPost,
  productCategory,
  product,
  solutionGroup,
  solutionChild,
  seoEntry,
  uiMessages,
  redirect,
  formSubmission,
];

export const singletonTypes = new Set([
  "siteSettings",
  "homePage",
  "aboutPage",
  "contactPage",
  "productsPage",
  "solutionsPage",
  "blogPage",
]);
